stages:
  - build-image

.job_template: &build_image_definition_dh
  image: docker:19
  stage: build-image
  services:
    - alias: docker
      name: docker:19.03.5-dind
  script:
    - apk add --no-cache bash
    - bash ./ci_docker_build_push.sh
  variables: &extended_image_vars_dh
    REGISTRY_USER: "${DH_CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${DH_CI_REGISTRY_PASSWORD}"
    REGISTRY: "${DH_CI_REGISTRY}"
    DOCKER_NAME: "postgresai/migration-tools"

.job_template: &build_image_definition_gl
  image: docker:19
  stage: build-image
  services:
    - alias: docker
      name: docker:19.03.5-dind
  script:
    - apk add --no-cache bash
    - bash ./ci_docker_build_push.sh
  variables: &extended_image_vars_gl
    REGISTRY_USER: "${CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
    REGISTRY: "${CI_REGISTRY}"
    DOCKER_NAME: "registry.gitlab.com/postgres-ai/custom-images/migration-tools"

.only_var_template: &only_tag_release
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^[0-9.]+$/
    changes:
      - migration-tools/*

.only_var_template: &only_feature
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_SLUG != "master"
    changes:
      - migration-tools/*
  when: manual

build-sqitch-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    TOOL_NAME: "sqitch"
    DOCKER_FILE: "migration-tools/sqitch.Dockerfile"
    TAGS: "${DOCKER_NAME}:${TOOL_NAME},${DOCKER_NAME}:${TOOL_NAME}-${CI_COMMIT_TAG}"

build-flyway-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    TOOL_NAME: "flyway"
    DOCKER_FILE: "migration-tools/flyway.Dockerfile"
    TAGS: "${DOCKER_NAME}:${TOOL_NAME},${DOCKER_NAME}:${TOOL_NAME}-${CI_COMMIT_TAG}"

build-liquibase-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    TOOL_NAME: "liquibase"
    DOCKER_FILE: "migration-tools/liquibase.Dockerfile"
    TAGS: "${DOCKER_NAME}:${TOOL_NAME},${DOCKER_NAME}:${TOOL_NAME}-${CI_COMMIT_TAG}"

build-rake-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    TOOL_NAME: "rake"
    DOCKER_FILE: "migration-tools/rake.Dockerfile"
    TAGS: "${DOCKER_NAME}:${TOOL_NAME},${DOCKER_NAME}:${TOOL_NAME}-${CI_COMMIT_TAG}"

build-django-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    TOOL_NAME: "django"
    DOCKER_FILE: "migration-tools/django.Dockerfile"
    TAGS: "${DOCKER_NAME}:${TOOL_NAME},${DOCKER_NAME}:${TOOL_NAME}-${CI_COMMIT_TAG}"

build-sqitch-image-feature:
  <<: *build_image_definition_gl
  <<: *only_feature
  variables:
    <<: *extended_image_vars_gl
    TOOL_NAME: "sqitch"
    DOCKER_FILE: "migration-tools/sqitch.Dockerfile"
    TAGS: "${DOCKER_NAME}:${TOOL_NAME},${DOCKER_NAME}:${TOOL_NAME}-${CI_COMMIT_REF_SLUG}"


build-flyway-image-feature:
  <<: *build_image_definition_gl
  <<: *only_feature
  variables:
    <<: *extended_image_vars_gl
    TOOL_NAME: "flyway"
    DOCKER_FILE: "migration-tools/flyway.Dockerfile"
    TAGS: "${DOCKER_NAME}:${TOOL_NAME},${DOCKER_NAME}:${TOOL_NAME}-${CI_COMMIT_REF_SLUG}"

build-liquibase-image-feature:
  <<: *build_image_definition_gl
  <<: *only_feature
  variables:
    <<: *extended_image_vars_gl
    TOOL_NAME: "liquibase"
    DOCKER_FILE: "migration-tools/liquibase.Dockerfile"
    TAGS: "${DOCKER_NAME}:${TOOL_NAME},${DOCKER_NAME}:${TOOL_NAME}-${CI_COMMIT_REF_SLUG}"

build-rake-image-feature:
  <<: *build_image_definition_gl
  <<: *only_feature
  variables:
    <<: *extended_image_vars_gl
    TOOL_NAME: "rake"
    DOCKER_FILE: "migration-tools/rake.Dockerfile"
    TAGS: "${DOCKER_NAME}:${TOOL_NAME},${DOCKER_NAME}:${TOOL_NAME}-${CI_COMMIT_REF_SLUG}"

build-django-image-feature:
  <<: *build_image_definition_gl
  <<: *only_feature
  variables:
    <<: *extended_image_vars_gl
    TOOL_NAME: "django"
    DOCKER_FILE: "migration-tools/django.Dockerfile"
    TAGS: "${DOCKER_NAME}:${TOOL_NAME},${DOCKER_NAME}:${TOOL_NAME}-${CI_COMMIT_REF_SLUG}"
