stages:
  - build-image
  - build-extended-image

.job_template: &build_image_definition_dh
  image: docker:19
  stage: build-image
  services:
    - alias: docker
      name: docker:19.03.5-dind
  script:
    - apk add --no-cache bash
    - bash ./ci_docker_build_push.sh
  variables: &extended_image_vars_dh
    REGISTRY_USER: "${DH_CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${DH_CI_REGISTRY_PASSWORD}"
    REGISTRY: "${DH_CI_REGISTRY}"
    DOCKER_FILE: "extended-postgres/Dockerfile"
    DOCKER_NAME: "postgresai/extended-postgres"

.only_var_template: &only_tag_release
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^[0-9.]+$/

.only_var_template: &only_feature
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_SLUG != "master"
  when: manual

build-generic-postgres-9-6-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "9.6"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-10-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "10"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-11-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "11"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-12-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "12"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-13-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "13"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-14-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "14"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-15-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "15"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-images:
  stage: build-image
  <<: *only_feature
  trigger:
    include:
      - local: extended-postgres/generic-ci.yml

build-generic-postgis-images:
  stage: build-extended-image
  <<: *only_feature
  variables:
    SE_TYPE: postgis
  trigger:
    include:
      - local: extended-postgres/se-images-ci.yml
  needs:
    - job: build-generic-images

build-rds-images:
  stage: build-extended-image
  <<: *only_feature
  variables:
    SE_TYPE: rds
  trigger:
    include:
      - local: extended-postgres/se-images-ci.yml
  needs:
    - job: build-generic-images

build-supabase-images:
  stage: build-extended-image
  <<: *only_feature
  variables:
    SE_TYPE: supabase
  trigger:
    include:
      - local: extended-postgres/se-images-ci.yml

build-timescale-cloud-images:
  stage: build-extended-image
  <<: *only_feature
  variables:
    SE_TYPE: timescale-cloud
  trigger:
    include:
      - local: extended-postgres/se-images-ci.yml

build-heroku-images:
  stage: build-extended-image
  <<: *only_feature
  variables:
    SE_TYPE: heroku
  trigger:
    include:
      - local: extended-postgres/se-images-ci.yml
