stages:
  - build-image
  - build-extended-image

.job_template: &build_image_definition_dh
  image: docker:19
  stage: build-image
  services:
    - alias: docker
      name: docker:19.03.5-dind
  script:
    - apk add --no-cache bash
    - bash ./ci_docker_build_push.sh
  variables: &extended_image_vars_dh
    REGISTRY_USER: "${DH_CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${DH_CI_REGISTRY_PASSWORD}"
    REGISTRY: "${DH_CI_REGISTRY}"
    DOCKER_FILE: "extended-postgres/Dockerfile"
    DOCKER_NAME: "postgresai/extended-postgres"

.only-tag-template: &only_tag_release
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9.]+$/
      when: manual

.only-feature-template: &only_feature
  rules:
    - if: $CI_BUILD_EXTENSION != null
      when: never
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_REF_SLUG != "master"
      when: manual

build-generic-postgres-9-6-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "9.6"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-10-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "10"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-11-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "11"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-12-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "12"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-13-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "13"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-14-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "14"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-generic-postgres-15-image-latest:
  <<: *build_image_definition_dh
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_dh
    PG_SERVER_VERSION: "15"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

# Debug
.build-generic-images:
  stage: build-image
  <<: *only_feature
  trigger:
    include: extended-postgres/generic-ci.yml
    # strategy: depend # DEBUG

build-se-images:
  stage: build-extended-image
  rules:
    - !reference [.only-feature-template, rules]
  variables:
    BASE_COMMIT_REF: $CI_COMMIT_REF_SLUG
  trigger:
    project: postgres-ai/se-images
    branch: '463-move-se-images'
#    strategy: depend # DEBUG

build-se-images-release:
  stage: build-extended-image
  rules:
    - !reference [.only-tag-template, rules]
  variables:
    COMMIT_TAG: 0.0.0 #$CI_COMMIT_TAG
  trigger:
    project: postgres-ai/se-images
    branch: '463-move-se-images'
#    strategy: depend # DEBUG

