stages:
  - build-extended-image

.se_feature_job_template: &build_image_definition_gl
  image: docker:19
  stage: build-extended-image
  services:
    - alias: docker
      name: docker:19.03.5-dind
  before_script:
    - export PLV8_VERSION=3.1.4
  script:
      - apk add --no-cache bash curl
      - export PLV8_PACKAGE_NAME=postgresql-${PG_SERVER_VERSION}-plv8
      - 'curl -O plv8.tar.gz -XGET --header "JOB-TOKEN: ${CI_JOB_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PLV8_PACKAGE_NAME}/${PLV8_VERSION}/plv8-${PLV8_VERSION}.tar.gz"'
      - bash ./ci_docker_build_push.sh
  variables: &extended_image_vars_gl
    REGISTRY_USER: "${CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
    REGISTRY: "${CI_REGISTRY}"
    DOCKER_FILE: "extended-postgres/Dockerfile.${SE_TYPE}"
    BASE_IMAGE_NAME: "${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/extended-postgres"
    BASE_COMMIT_REF: "-${CI_COMMIT_REF_SLUG}"
    DOCKER_NAME: "${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/extended-postgres-${SE_TYPE}"
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
#  tags:
#    - runner-build

.only_tag_template: &only_tag_release
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^[0-9.]+$/

.only_branch_template: &only_branch
  rules:
    - if: $CI_BUILD_EXTENSION != null
      when: never
    - if: $CI_COMMIT_REF_SLUG != "master"
      when: manual

build-extended-postgres-9-6-branch:
  <<: *build_image_definition_gl
  <<: *only_branch
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "9.6"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_REF_SLUG}"

build-extended-postgres-10-branch:
  <<: *build_image_definition_gl
  <<: *only_branch
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "10"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_REF_SLUG}"

build-extended-postgres-11-branch:
  <<: *build_image_definition_gl
  <<: *only_branch
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "11"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_REF_SLUG}"

build-extended-postgres-12-branch:
  <<: *build_image_definition_gl
  <<: *only_branch
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "12"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_REF_SLUG}"

build-extended-postgres-13-branch:
  <<: *build_image_definition_gl
  <<: *only_branch
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "13"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_REF_SLUG}"

build-extended-postgres-14-branch:
  <<: *build_image_definition_gl
  <<: *only_branch
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "14"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_REF_SLUG}"

build-extended-postgres-15-branch:
  <<: *build_image_definition_gl
  <<: *only_branch
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "15"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_REF_SLUG}"


## Release jobs
build-extended-postgres-9-6-release:
  <<: *build_image_definition_gl
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "9.6"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-extended-postgres-10-release:
  <<: *build_image_definition_gl
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "10"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-extended-postgres-11-release:
  <<: *build_image_definition_gl
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "11"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-extended-postgres-12-release:
  <<: *build_image_definition_gl
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "12"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-extended-postgres-13-release:
  <<: *build_image_definition_gl
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "13"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-extended-postgres-14-release:
  <<: *build_image_definition_gl
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "14"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"

build-extended-postgres-15-release:
  <<: *build_image_definition_gl
  <<: *only_tag_release
  variables:
    <<: *extended_image_vars_gl
    PG_SERVER_VERSION: "15"
    TAGS: "${DOCKER_NAME}:${PG_SERVER_VERSION},${DOCKER_NAME}:${PG_SERVER_VERSION}-${CI_COMMIT_TAG}"
